SHOW COLUMNS FROM customer;

#Q1 What is total revenue generated by male vs female customers.
SELECT Gender, SUM(CAST(`Purchase Amount (USD)` AS DECIMAL(10,2))) AS revenue
FROM customer
GROUP BY Gender;

#Q2 which customers use discount but stiil spend more thean the average purchase amount?
SELECT `Customer ID`,`Purchase Amount (USD)`
FROM customer
WHERE `Discount Applied` = 'yes'AND `Purchase Amount (USD)` >= (SELECT AVG(`Purchase Amount (USD)`) FROM customer);

#Q3 which are the top 5 products with the highest average review rating.
SELECT `Item Purchased`,AVG(`Review Rating`) as "Average Product Rating"
FROM customer
group by `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;

#4 - compare the average purchase amounts between standard and express shipping
SELECT `shipping type`,
AVG (`Purchase Amount (USD)`)
FROM customer
WHERE `shipping type` IN ('standard','Express')
GROUP BY `shipping type`


#Q5 Do subscribed customers spend more ? compare average spend and total revenue subscibers and non-subscribers.
SELECT `Subscription Status` as Subscription_Status,
count(`Customer ID`) as total_customers,
AVG (`Purchase Amount (USD)`) as avg_spend,
sum(`Purchase Amount (USD)`) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend,total_revenue DESC

#Q6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
round(100 * sum(CASE WHEN `Discount Applied`='Yes' THEN 1 ELSE 0 END)/count(*) ,2) as discount_rate
from customer
group by `Item Purchased`
order by discount_rate desc
limit 5;

# Q7 Segment customers into New,Returning and Loyal based on their total number of previous purchases and show the count of each segment.
with customer_type as(
select `Customer Id`,`Previous Purchases`,
CASE 
    when `Previous Purchases`=1 THEN 'New'
    WHEN `Previous Purchases` between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segment
from customer
)

#Q8 What are thebtop 3 most purchased products within each category?
SELECT *
FROM(
	SELECT `Category`,
           `Item Purchased`,
            total_orders,
			ROW_NUMBER() OVER (PARTITION BY Category ORDER BY total_orders DESC) AS item_rank
    FROM (
        SELECT `Category`,
               `Item Purchased`,
               COUNT(`Customer ID`) AS total_orders
        FROM customer
    GROUP BY `Category`, `Item Purchased`
) t
) r
WHERE item_rank <= 3;

#Q9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select `Subscription Status`,
count(`Customer ID`) as repeat_buyers
from customer
where `Previous Purchases` > 5
group by `Subscription Status`

#Q10 What is the revenue contribution of each age group.
select `Age`,
sum(`Purchase Amount (USD)`) as total_revenue
from customer
group by `Age`
order by total_revenue desc;
